[mcmc_settings]
tune = 1000
draws = 2000
chains = 4
target_accept = 0.99
nuts_sampler = "numpyro"
random_seed = 42
show_progress_bar = false     # Enable or disable the sampling progress bar

[initial_values]
# Starting points for the MCMC chains
kappa = 1.0
alpha = 30.0
gamma = 2.0
k = 1.0
sigma_0 = 1.0
sigma_1 = 7.0